version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env.test
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests