name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint&test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        volumes:
          - /var/lib/postgresql/data
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
        
      - name: Run tests
        run: npm run test:action
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/test_db?schema=public"
